// Code generated by scripts/generate-go.ts from gospec/schema.json (v0.1.0).
// DO NOT EDIT. To change these types, edit src/schema.ts and regenerate.

package gospec

import (
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/santhosh-tekuri/jsonschema/v5"
)

// schema.json is the canonical Dashbones JSON Schema, generated from the
// TypeScript/Zod schema in this repository. It is the single source of truth
// that keeps the Go and TypeScript implementations in sync.
//
//go:embed schema.json
var schemaJSON []byte

var compiled *jsonschema.Schema

func init() {
	var err error
	compiled, err = jsonschema.CompileString("dashbones.json", string(schemaJSON))
	if err != nil {
		panic(fmt.Sprintf("gospec: failed to compile embedded schema: %v", err))
	}
}

// Validate checks raw wire-format bytes against the canonical JSON Schema and
// the Dashbones layout rules (x-layout annotations). It rejects unknown fields,
// missing required fields, out-of-range columns, invalid themes, and similarly
// encoded data.
func Validate(data []byte) error {
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return fmt.Errorf("gospec: invalid JSON: %w", err)
	}
	if err := compiled.Validate(v); err != nil {
		return fmt.Errorf("gospec: schema validation failed: %w", err)
	}
	var d Dashboard
	if err := json.Unmarshal(data, &d); err != nil {
		return fmt.Errorf("gospec: parse for layout check: %w", err)
	}
	if err := checkLayout(&d); err != nil {
		return err
	}
	return nil
}
