#!/usr/bin/env node
/**
 * Generates the Go package in gospec/ (dashbones.go + validate.go) from the
 * canonical JSON Schema at gospec/schema.json — the single source of truth.
 *
 * The emission is fully deterministic: run `npm run gen:go` (or `make gen-go`)
 * and the generated files are byte-identical to what is committed. Hand-editing
 * the generated .go files is not supported; change the schema instead.
 *
 * The generated code mirrors the behavior of the TS/Zod implementation:
 *   - "anyOf:[{type:"boolean"}, {const:"true"}, {const:"false"}]" fields
 *     become a Bool type that accepts real booleans and "true"/"false" strings
 *   - object properties with required red/green/blue/alpha become *RGBColor
 *   - the boxes.items "oneOf" union is lowered into a BaseBox + per-variant
 *     structs and a tagged-union Box with JSON dispatch
 *   - the boxes.items "x-layout" annotations (emitted from src/layout.ts) become
 *     checkLayout(), the same cross-field rules Zod enforces via .check()
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import pkg from "../package.json" with { type: "json" };

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GO_DIR = join(ROOT, "gospec");

interface JsonSchema {
  type?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  oneOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  items?: JsonSchema;
  enum?: unknown[];
  const?: unknown;
}

const HEADER = `// Code generated by scripts/generate-go.ts from gospec/schema.json (v${pkg.version}).
// DO NOT EDIT. To change these types, edit src/schema.ts and regenerate.
`;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// Capitalize a JSON key into an exported Go identifier.
function goIdent(key: string): string {
  const fixed: Record<string, string> = { url: "URL", id: "ID" };
  return fixed[key] ?? key.charAt(0).toUpperCase() + key.slice(1);
}

function isBool(schemas: JsonSchema | undefined): boolean {
  if (!schemas || !Array.isArray(schemas.anyOf)) return false;
  return schemas.anyOf.some((m) => m.type === "boolean");
}

function isColor(s: JsonSchema | undefined): boolean {
  const req = s?.required;
  return (
    s?.type === "object" &&
    Boolean(req) &&
    ["red", "green", "blue", "alpha"].every((c) => req!.includes(c)) &&
    ["red", "green", "blue", "alpha"].every(
      (c) => s.properties?.[c]?.type === "number",
    )
  );
}

function goType(s: JsonSchema | undefined): string {
  if (isBool(s)) return "Bool";
  if (isColor(s)) return "*RGBColor";
  switch (s?.type) {
    case "integer":
      return "int";
    case "number":
      return "float64";
    case "array":
      return `[]${s.items?.type === "integer" ? "int" : "float64"}`;
    case "string":
      return "string";
    default:
      throw new Error(`cannot map schema to a Go type: ${JSON.stringify(s)}`);
  }
}

function jsonTag(name: string, required: boolean): string {
  return `json:"${name}${required ? "" : ",omitempty"}"`;
}

function fieldLine(
  prefix: string,
  ident: string,
  type: string,
  tag: string,
): string {
  return `${prefix}${ident} ${type} \`${tag}\``;
}

// ---------------------------------------------------------------------------
// analysis
// ---------------------------------------------------------------------------

function analyze() {
  const schema: JsonSchema = JSON.parse(
    readFileSync(join(GO_DIR, "schema.json"), "utf8"),
  );

  const rootProps = schema.properties!;
  const rootRequired = new Set(schema.required ?? []);

  const boxItems = rootProps.boxes!.items!;
  const branches = boxItems.oneOf!.map((branch) => {
    const t = branch.properties!.type;
    const types: string[] = [];
    if (typeof t?.const === "string") types.push(t.const);
    else if (Array.isArray(t?.anyOf)) {
      for (const m of t.anyOf) {
        if (typeof m.const === "string") types.push(m.const);
      }
    }
    if (types.length === 0) {
      throw new Error(`branch has no const type discriminator: ${JSON.stringify(branch)}`);
    }
    return { branch, types };
  });

  const allKeys = new Set<string>();
  for (const { branch } of branches) {
    for (const key of Object.keys(branch.properties!)) allKeys.add(key);
  }

  // Keys present on every variant belong in BaseBox.
  const commonKeys = [...allKeys].filter((key) =>
    branches.every((b) => key in b.branch.properties!),
  );

  const firstBranch = branches[0].branch;

  const variantName = (types: string[]): string => `${goIdent(types[0])}Box`;

  const constFor = (type: string): string => `Box${type}`;

  const layoutAnnotations: {
    rule: string;
    types: string[];
  }[] = Array.isArray(boxItems["x-layout"])
    ? boxItems["x-layout"]
    : [];

  return {
    schema,
    rootProps,
    rootRequired,
    branches,
    commonKeys,
    firstBranch,
    variantName,
    constFor,
    layoutAnnotations,
  };
}

// ---------------------------------------------------------------------------
// emission
// ---------------------------------------------------------------------------

function emitDashbones(a = analyze()): string {
  const L: string[] = [];
  const p = (s = "") => L.push(s);

  p(HEADER);
  p(`package gospec`);
  p();
  p(`import (`);
  p(`\t"encoding/json"`);
  p(`\t"errors"`);
  p(`\t"fmt"`);
  p(`)`);
  p();

  // --- Bool -----------------------------------------------------------------
  p(`// Bool decodes the Dashbones boolean wire format, which accepts both real`);
  p(`// booleans and the string literals "true"/"false" (as used by the official`);
  p(`// demo). It always marshals as a real JSON boolean.`);
  p(`type Bool bool`);
  p();
  p(`// UnmarshalJSON implements json.Unmarshaler for Bool.`);
  p(`func (b *Bool) UnmarshalJSON(data []byte) error {`);
  p(`\tvar v any`);
  p(`\tif err := json.Unmarshal(data, &v); err != nil {`);
  p(`\t\treturn err`);
  p(`\t}`);
  p(`\tswitch x := v.(type) {`);
  p(`\tcase bool:`);
  p(`\t\t*b = Bool(x)`);
  p(`\t\treturn nil`);
  p(`\tcase string:`);
  p(`\t\tswitch x {`);
  p(`\t\tcase "true":`);
  p(`\t\t\t*b = true`);
  p(`\t\t\treturn nil`);
  p(`\t\tcase "false":`);
  p(`\t\t\t*b = false`);
  p(`\t\t\treturn nil`);
  p(`\t\t}`);
  p(`\t}`);
  p(`\treturn fmt.Errorf("gospec: invalid boolean value: %s", string(data))`);
  p(`}`);
  p();
  p(`// MarshalJSON implements json.Marshaler for Bool.`);
  p(`func (b Bool) MarshalJSON() ([]byte, error) {`);
  p(`\tif b {`);
  p(`\t\treturn []byte("true"), nil`);
  p(`\t}`);
  p(`\treturn []byte("false"), nil`);
  p(`}`);
  p();

  // --- RGBColor -------------------------------------------------------------
  p(`// RGBColor is an RGBa color dictionary used for theme overrides and per-box`);
  p(`// backgrounds. Channels are numbers (typically 0-255, alpha 0-1).`);
  p(`type RGBColor struct {`);
  for (const c of ["red", "green", "blue", "alpha"]) {
    p(fieldLine("\t", goIdent(c), "float64", jsonTag(c, true)));
  }
  p(`}`);
  p();

  // --- Theme ----------------------------------------------------------------
  const themeSchema = a.rootProps.theme!;
  p(`// Theme is one of the predefined Dashbones theme names.`);
  p(`type Theme string`);
  p();
  p(`// Supported theme values.`);
  p(`const (`);
  for (const value of (themeSchema.enum ?? []) as string[]) {
    p(`\tTheme${goIdent(value)} Theme = "${value}"`);
  }
  p(`)`);
  p();

  // --- BoxType --------------------------------------------------------------
  const boxTypes: string[] = [];
  for (const b of a.branches) {
    for (const t of b.types) {
      if (!boxTypes.includes(t)) boxTypes.push(t);
    }
  }
  p(`// BoxType discriminates the box variants.`);
  p(`type BoxType string`);
  p();
  p(`// Supported box type values.`);
  p(`const (`);
  for (const type of boxTypes) {
    p(`\tBox${type} BoxType = "${type}"`);
  }
  p(`)`);
  p();

  // --- Dashboard ------------------------------------------------------------
  const dashFields = Object.keys(a.rootProps);
  p(`// Dashboard is the top-level Dashbones document.`);
  p(`type Dashboard struct {`);
  for (const key of dashFields) {
    const prop = a.rootProps[key]!;
    const required = a.rootRequired.has(key);
    const ident = goIdent(key);
    const type = key === "theme" ? "Theme" : key === "boxes" ? "[]Box" : goType(prop);
    p(fieldLine("\t", ident, type, jsonTag(key, required)));
  }
  p(`}`);
  p();

  // --- BaseBox + variants ---------------------------------------------------
  const firstProps = a.firstBranch.properties!;
  p(`// BaseBox holds the fields shared by every box type.`);
  p(`type BaseBox struct {`);
  for (const key of Object.keys(firstProps)) {
    if (!a.commonKeys.includes(key)) continue;
    const required = a.branches.every((b) =>
      b.branch.required?.includes(key),
    );
    const ident = goIdent(key);
    const type = key === "type" ? "BoxType" : goType(firstProps[key]);
    p(fieldLine("\t", ident, type, jsonTag(key, required)));
  }
  p(`}`);
  p();

  const variantDoc: Record<string, string> = {
    SimpleBox: `// SimpleBox is a single line of text.`,
    StackedBox: `// StackedBox is two lines of text (type "Stacked" or "Stack").`,
    TableBox: `// TableBox shows a headline and up to two header rows.`,
    DeltaBox: `// DeltaBox is a headline with a small delta value behind it. Deltas are two`,
    ChartBox: `// ChartBox renders a bar chart from data.`,
    ImageBox: `// ImageBox displays an image from a URL.`,
  };

  for (const b of a.branches) {
    const name = a.variantName(b.types);
    p(variantDoc[name] ?? `// ${name} is a Dashbones box variant.`);
    p(`type ${name} struct {`);
    p(`\tBaseBox`);
    for (const key of Object.keys(b.branch.properties!)) {
      if (key === "type" || a.commonKeys.includes(key)) continue;
      const prop = b.branch.properties![key];
      const required = b.branch.required?.includes(key) ?? false;
      p(fieldLine("\t", goIdent(key), goType(prop), jsonTag(key, required)));
    }
    p(`}`);
    p();
  }

  // --- Box union ------------------------------------------------------------
  p(`// Box is a discriminated union over the box types. Exactly one variant is`);
  p(`// populated, matching the box's "type".`);
  p(`type Box struct {`);
  p(`\tType    BoxType`);
  for (const b of a.branches) {
    const field = b.types[0];
    p(`\t${field}  *${a.variantName(b.types)}`);
  }
  p(`}`);
  p();

  // --- dispatch ------------------------------------------------------------
  p(`// UnmarshalJSON dispatches on the "type" discriminator.`);
  p(`func (b *Box) UnmarshalJSON(data []byte) error {`);
  p(`\tvar probe struct {`);
  p(`\t\tType BoxType \`json:"type"\``);
  p(`\t}`);
  p(`\tif err := json.Unmarshal(data, &probe); err != nil {`);
  p(`\t\treturn err`);
  p(`\t}`);
  p(`\tb.Type = probe.Type`);
  p(`\tswitch probe.Type {`);
  for (const br of a.branches) {
    const labels = br.types.map((t) => a.constFor(t)).join(", ");
    p(`\tcase ${labels}:`);
    p(`\t\tvar v ${a.variantName(br.types)}`);
    p(`\t\tif err := json.Unmarshal(data, &v); err != nil {`);
    p(`\t\t\treturn err`);
    p(`\t\t}`);
    p(`\t\tb.${br.types[0]} = &v`);
  }
  p(`\tdefault:`);
  p(`\t\treturn fmt.Errorf("gospec: unknown box type %q", probe.Type)`);
  p(`\t}`);
  p(`\treturn nil`);
  p(`}`);
  p();

  p(`// MarshalJSON serializes the populated variant.`);
  p(`func (b *Box) MarshalJSON() ([]byte, error) {`);
  p(`\tswitch b.Type {`);
  for (const br of a.branches) {
    const labels = br.types.map((t) => a.constFor(t)).join(", ");
    const field = br.types[0];
    p(`\tcase ${labels}:`);
    p(`\t\tif b.${field} == nil {`);
    p(`\t\t\treturn nil, errors.New("gospec: Box of type ${field} has nil payload")`);
    p(`\t\t}`);
    p(`\t\treturn json.Marshal(b.${field})`);
  }
  p(`\tdefault:`);
  p(`\t\treturn nil, fmt.Errorf("gospec: unknown box type %q", b.Type)`);
  p(`\t}`);
  p(`}`);
  p();

  // --- baseBox --------------------------------------------------------------
  p(`// baseBox returns the common field set for the populated variant, or nil if`);
  p(`// no variant is populated.`);
  p(`func (b *Box) baseBox() *BaseBox {`);
  p(`\tswitch b.Type {`);
  for (const br of a.branches) {
    const labels = br.types.map((t) => a.constFor(t)).join(", ");
    const field = br.types[0];
    p(`\tcase ${labels}:`);
    p(`\t\tif b.${field} != nil {`);
    p(`\t\t\treturn &b.${field}.BaseBox`);
    p(`\t\t}`);
  }
  p(`\t}`);
  p(`\treturn nil`);
  p(`}`);
  p();

  // --- checkLayout ----------------------------------------------------------
  p(`// checkLayout enforces the cross-field layout rules from the schema's`);
  p(`// x-layout annotations.`);
  p(`func checkLayout(d *Dashboard) error {`);
  p(`\tfor i := range d.Boxes {`);
  p(`\t\tb := &d.Boxes[i]`);
  p(`\t\tbb := b.baseBox()`);
  p(`\t\tif bb == nil {`);
  p(`\t\t\treturn fmt.Errorf("gospec: box %d has no payload", i)`);
  p(`\t\t}`);
  p(`\t\tswitch b.Type {`);

  // Group box types by the layout checks that apply to them.
  const checksFor = (type: string): string[] => {
    const out: string[] = [];
    for (const r of a.layoutAnnotations) {
      if (!r.types.includes(type)) continue;
      if (r.rule === "evenColumn") {
        out.push(`if bb.Column%2 != 0 {`);
        out.push(`\treturn fmt.Errorf("gospec: ${type} box %d must start on an even column, got %d", i, bb.Column)`);
        out.push(`}`);
      } else if (r.rule === "notZoomed") {
        out.push(`if bb.Zoomed {`);
        out.push(`\treturn fmt.Errorf("gospec: ${type} box %d cannot be zoomed", i)`);
        out.push(`}`);
      } else if (r.rule === "zoomedRequiresEvenColumn") {
        out.push(`if bb.Zoomed && bb.Column%2 != 0 {`);
        out.push(`\treturn fmt.Errorf("gospec: zoomed box %d must be on an even column", i)`);
        out.push(`}`);
      }
    }
    return out;
  };

  interface Group {
    labels: string;
    checks: string[];
    indent: string;
  }
  const groups: Group[] = [];
  for (const br of a.branches) {
    const checks = checksFor(br.types[0]);
    // de-dup the "case" prefix on the lines we generate:
    const label = br.types.map((t) => a.constFor(t)).join(", ");
    const existing = groups.find((g) => g.checks.join("\n") === checks.join("\n"));
    if (existing) {
      existing.labels += `, ${label}`;
    } else {
      groups.push({ labels: label, checks, indent: "\t\t" });
    }
  }
  for (const g of groups) {
    p(`\t\tcase ${g.labels}:`);
    for (const line of g.checks) {
      p(`${g.indent}${line}`);
    }
  }
  p(`\t\t}`);
  p(`\t}`);
  p(`\treturn nil`);
  p(`}`);
  p();

  // --- package-level helpers ------------------------------------------------
  p(`// Unmarshal decodes a Dashboard from JSON bytes. It uses encoding/json and`);
  p(`// does not enforce cross-field layout rules; call Validate for full schema`);
  p(`// validation of the raw wire data.`);
  p(`func Unmarshal(data []byte) (*Dashboard, error) {`);
  p(`\tvar d Dashboard`);
  p(`\tif err := json.Unmarshal(data, &d); err != nil {`);
  p(`\t\treturn nil, err`);
  p(`\t}`);
  p(`\treturn &d, nil`);
  p(`}`);
  p();
  p(`// Marshal encodes a Dashboard to JSON bytes.`);
  p(`func Marshal(d *Dashboard) ([]byte, error) {`);
  p(`\treturn json.Marshal(d)`);
  p(`}`);

  return L.join("\n") + "\n";
}

function emitValidate(a = analyze()): string {
  const L: string[] = [];
  const p = (s = "") => L.push(s);

  p(HEADER);
  p(`package gospec`);
  p();
  p(`import (`);
  p(`\t_ "embed"`);
  p(`\t"encoding/json"`);
  p(`\t"fmt"`);
  p();
  p(`\t"github.com/santhosh-tekuri/jsonschema/v5"`);
  p(`)`);
  p();
  p(`// schema.json is the canonical Dashbones JSON Schema, generated from the`);
  p(`// TypeScript/Zod schema in this repository. It is the single source of truth`);
  p(`// that keeps the Go and TypeScript implementations in sync.`);
  p(`//`);
  p(`//go:embed schema.json`);
  p(`var schemaJSON []byte`);
  p();
  p(`var compiled *jsonschema.Schema`);
  p();
  p(`func init() {`);
  p(`\tvar err error`);
  p(`\tcompiled, err = jsonschema.CompileString("dashbones.json", string(schemaJSON))`);
  p(`\tif err != nil {`);
  p(`\t\tpanic(fmt.Sprintf("gospec: failed to compile embedded schema: %v", err))`);
  p(`\t}`);
  p(`}`);
  p();
  p(`// Validate checks raw wire-format bytes against the canonical JSON Schema and`);
  p(`// the Dashbones layout rules (x-layout annotations). It rejects unknown fields,`);
  p(`// missing required fields, out-of-range columns, invalid themes, and similarly`);
  p(`// encoded data.`);
  p(`func Validate(data []byte) error {`);
  p(`\tvar v any`);
  p(`\tif err := json.Unmarshal(data, &v); err != nil {`);
  p(`\t\treturn fmt.Errorf("gospec: invalid JSON: %w", err)`);
  p(`\t}`);
  p(`\tif err := compiled.Validate(v); err != nil {`);
  p(`\t\treturn fmt.Errorf("gospec: schema validation failed: %w", err)`);
  p(`\t}`);
  p(`\tvar d Dashboard`);
  p(`\tif err := json.Unmarshal(data, &d); err != nil {`);
  p(`\t\treturn fmt.Errorf("gospec: parse for layout check: %w", err)`);
  p(`\t}`);
  p(`\tif err := checkLayout(&d); err != nil {`);
  p(`\t\treturn err`);
  p(`\t}`);
  p(`\treturn nil`);
  p(`}`);

  return L.join("\n") + "\n";
}

for (const [file, content] of [
  ["dashbones.go", emitDashbones()],
  ["validate.go", emitValidate()],
] as const) {
  writeFileSync(join(GO_DIR, file), content);
  console.error(`generated gospec/${file}`);
}